import type { CronJob, AgentRun } from "./types";

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600_000).toISOString();
const minutesFromNow = (m: number) => new Date(now.getTime() + m * 60_000).toISOString();

export const mockCronJobs: CronJob[] = [
  {
    id: "cron-polymarket-odds",
    name: "Polymarket Odds Sync",
    schedule: "*/5 * * * *",
    schedule_human: "Every 5 minutes",
    last_run: minutesAgo(3),
    next_run: minutesFromNow(2),
    last_status: "success",
    consecutive_errors: 0,
    health: "green",
  },
  {
    id: "cron-trading-signals",
    name: "Trading Signal Scanner",
    schedule: "*/15 * * * *",
    schedule_human: "Every 15 minutes",
    last_run: minutesAgo(8),
    next_run: minutesFromNow(7),
    last_status: "success",
    consecutive_errors: 0,
    health: "green",
  },
  {
    id: "cron-grocery-prices",
    name: "Grocery Price Scraper",
    schedule: "0 */6 * * *",
    schedule_human: "Every 6 hours",
    last_run: hoursAgo(2),
    next_run: minutesFromNow(240),
    last_status: "success",
    consecutive_errors: 0,
    health: "green",
  },
  {
    id: "cron-crosslist-sync",
    name: "CrossList Inventory Sync",
    schedule: "0 */2 * * *",
    schedule_human: "Every 2 hours",
    last_run: hoursAgo(1),
    next_run: minutesFromNow(60),
    last_status: "warning",
    consecutive_errors: 1,
    health: "yellow",
  },
  {
    id: "cron-daily-digest",
    name: "Daily Digest Generator",
    schedule: "0 8 * * *",
    schedule_human: "Daily at 8:00 AM",
    last_run: hoursAgo(18),
    next_run: minutesFromNow(360),
    last_status: "success",
    consecutive_errors: 0,
    health: "green",
  },
  {
    id: "cron-portfolio-snapshot",
    name: "Portfolio Snapshot",
    schedule: "0 0 * * *",
    schedule_human: "Daily at midnight",
    last_run: hoursAgo(8),
    next_run: minutesFromNow(960),
    last_status: "error",
    consecutive_errors: 3,
    health: "red",
  },
  {
    id: "cron-arb-detector",
    name: "Arbitrage Detector",
    schedule: "*/2 * * * *",
    schedule_human: "Every 2 minutes",
    last_run: minutesAgo(1),
    next_run: minutesFromNow(1),
    last_status: "success",
    consecutive_errors: 0,
    health: "green",
  },
];

export const mockAgentRuns: AgentRun[] = [
  {
    id: "agent-001",
    agent_name: "CodeReview Agent",
    task: "Review PR #42 — add market correlation analysis",
    status: "completed",
    started_at: hoursAgo(2),
    finished_at: hoursAgo(1.8),
    duration_seconds: 720,
    repo: "daldc/trading-assistant",
  },
  {
    id: "agent-002",
    agent_name: "Research Agent",
    task: "Validate GrocerEase meal-plan feature demand",
    status: "completed",
    started_at: hoursAgo(5),
    finished_at: hoursAgo(4.5),
    duration_seconds: 1800,
    repo: "daldc/grocerease",
  },
  {
    id: "agent-003",
    agent_name: "Build Agent",
    task: "Scaffold CrossList eBay integration module",
    status: "running",
    started_at: minutesAgo(18),
    finished_at: null,
    duration_seconds: null,
    repo: "daldc/crosslist",
  },
  {
    id: "agent-004",
    agent_name: "Test Agent",
    task: "Run end-to-end tests for Polymarket order flow",
    status: "failed",
    started_at: hoursAgo(3),
    finished_at: hoursAgo(2.9),
    duration_seconds: 360,
    repo: "daldc/polymarket-arb",
  },
  {
    id: "agent-005",
    agent_name: "Deploy Agent",
    task: "Deploy trading-assistant v2.1.0 to production",
    status: "completed",
    started_at: hoursAgo(6),
    finished_at: hoursAgo(5.8),
    duration_seconds: 480,
    repo: "daldc/trading-assistant",
  },
  {
    id: "agent-006",
    agent_name: "Analysis Agent",
    task: "Generate weekly sprint velocity report",
    status: "timed_out",
    started_at: hoursAgo(8),
    finished_at: hoursAgo(7.5),
    duration_seconds: 1800,
    repo: "daldc/tasks",
  },
  {
    id: "agent-007",
    agent_name: "CodeReview Agent",
    task: "Review PR #15 — grocery price comparison engine",
    status: "completed",
    started_at: hoursAgo(1),
    finished_at: minutesAgo(30),
    duration_seconds: 1800,
    repo: "daldc/grocerease",
  },
];
